- hosts: kube-master
  gather_facts: True
  tasks:

  - pause:
      prompt: "Please run the drain command from master node"

  - name: install kubernetes binaries
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - "/app/data/upgrade-binaries/kubelet-1.19.0-0.x86_64.rpm"
      - "/app/data/upgrade-binaries/kubectl-1.19.0-0.x86_64.rpm"
      - "/app/data/upgrade-binaries/kubeadm-1.19.0-0.x86_64.rpm"
      - "/app/data/upgrade-binaries/cri-tools-1.13.0-0.x86_64.rpm"
      - "/app/data/upgrade-binaries/kubernetes-cni-0.8.7-0.x86_64.rpm"

  - name: copy the kubelet service file
    copy:
      src: /app/data/upgrade-binaries/kubelet.service
      dest: /usr/lib/systemd/system/kubelet.service
      mode: 755

  - name: kubernetes Upgrade --dry-run
    shell: /usr/bin/kubeadm upgrade apply --config=/app/data/upgrade-binaries/kubeadm-upgd-1.19.0.yaml --dry-run
    register: k8s_dryrun_v19
    when:
      ansible_hostname is search("m1")

  - debug:
      var=k8s_dryrun_v19.stdout.split('\n')

  - name: Saving output to /app/data/upgrade-binaries/k8s_dryrun_1.19.0.out
    copy:
      content: "{{ k8s_dryrun_v19 | to_nice_json }}"
      dest: /app/data/upgrade-binaries/k8s_dryrun_1.19.0.out

  - pause:
      prompt: "validate dry-run"

  - name: kubernetes Upgrade
    shell: /usr/bin/kubeadm upgrade apply --config=/app/data/upgrade-binaries/kubeadm-upgd-1.19.0.yaml -f
    register: k8s_upgd_v19
    when:
      ansible_hostname is search("m1")

  - debug:
      var=k8s_upgd_v19.stdout.split('\n')

  - name: Saving output to /app/data/upgrade-binaries/k8s_upgd_1.19.0.out
    copy:
      content: "{{ k8s_upgd_v19 | to_nice_json }}"
      dest: /app/data/upgrade-binaries/k8s_upgd_1.19.0.out


  - pause:
      prompt: "Proceed with kubelet restart"


  - name: Reload,enable and restart kubelet
    systemd:
      name: kubelet
      state: restarted
      daemon_reload: true
      enabled: yes

  - name: Remove kubernetes directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /usr/local/bin/kubeadm
      - /usr/local/bin/kubelet
      - /usr/local/bin/kubectl

  - pause:
      prompt: "Please run the uncordon command from master node"

  tags:
  - k8s-master-1.19.0
